### ISSUE TITLE
Question: What does KEY=32_character_encryption_key stand for??

### ISSUE THREAD

**Issue by CyberDudeJ** [ZeppelinBot/Zeppelin#235]
Just wondering what KEY=32_character_encryption_key stands for

**Comment by harshfeudal** [comment]
> It's a personal encryption key that's used with the [`crypto.createCipheriv`](https://nodejs.org/api/crypto.html#crypto_crypto_createcipheriv_algorithm_key_iv_options) method to encrypt values at rest.

How can I use it? Do I need to generate it or where will I pick it?

**Comment by almeidx** [comment]
You just have to set it to a string with 32 characters

**Comment by harshfeudal** [comment]
I mean it is a string but where I collect that string? or will I need to do the same like OpenSSL? I'm sorry a lot because I'm a C++ Discord bot maker not a JS/TS so I may misunderstand :(

**Comment by almeidx** [comment]
Just make it up, or generate it randomly, does not matter. As long as it has 32 characters

**Comment by harshfeudal** [comment]
lmao okay I'll pick it randomly
