### ISSUE TITLE
What to do with the built dashboard?

### ISSUE THREAD

**Issue by AndrewDragonCh** [ZeppelinBot/Zeppelin#267]
I have built the folder following the instructions, and have moved the contents of the `dist/` folder to the `www/` folder on my computers WAMP server.

![www folder](https://user-images.githubusercontent.com/43673678/131180174-56822edf-0ac4-437b-b722-b7cd290058f5.PNG)

But, when I go to [localhost](http://localhost/), the dashboard button doesn't work, which makes sense, since there are no folders inside of the `dist/` folder. What needs to be done that I am missing? Is it an issue with [localhost](http://localhost/)? Thanks

**Comment by metal0** [comment]
could try hosting it on a real domain. haven't tested localhost before and I can see some reasons as to why it might not work properly.
