### ISSUE TITLE
Exclude_categories seems to have stopped working somewhat recently

### ISSUE THREAD

**Issue by mrmangohands** [ZeppelinBot/Zeppelin#312]
For message logging exclude_categories seems to be broken, tested in two different servers. Exclude_channels is still fine though.

**Comment by Infinidoge** [comment]
The specific issue, as I understand it, is that message edits to not properly include the message category when running the log function.

Relevant lines here: https://github.com/ZeppelinBot/Zeppelin/blob/3cf08e5a49650bb457636f599a39838121eb8cf4/backend/src/plugins/Logs/logFunctions/logMessageEdit.ts#L26-L37

This has been a pretty big problem on my end, and required a large number of channels to be explicitly ignored. Given that this appears to be a simple fix, hopefully it can be fixed soon.

**Comment by metal0** [comment]
looks like this was fixed
