### ISSUE TITLE
Getting "Environment value KEY required for encryption" on startup

### ISSUE THREAD

**Issue by ExPort-Gaming** [ZeppelinBot/Zeppelin#350]
Hi, I'm getting "Environment value KEY required for encryption" on startup. How do I fix it?

**Comment by almeidx** [comment]
You didn't set the `KEY` on the root .env file

**Comment by ExPort-Gaming** [comment]
> You didn't set the `KEY` on the root .env file

And where can I find that file?

**Comment by ExPort-Gaming** [comment]
Nevermind, found it.
