### ISSUE TITLE
Where to set global config? 

### ISSUE THREAD

**Issue by msimon** [ZeppelinBot/Zeppelin#379]
I noticed that `Zeppelin/backend/src/pluginUtils.ts` uses `knub.getGlobalConfig()` to get the url of the server.
And that the config is set in `getConfig` in `new Knub<ZeppelinGuildConfig, ZeppelinGlobalConfig>` constructor. 

But I am not seeing anywhere a way to set the global config. In my DB, there isn't any config with a "global" key.

There is `backend/src/migrateConfigsToDB.ts` that, I'm guessing, was used once to move a config file to the DB, but nothing else.

Let me know if I'm missing something.

**Comment by rubyowo** [comment]
You'd add the global config under the `configs` table, and set the key to `global`.
Here's an example:
INSERT INTO configs (`key`, config, is_active, edited_by) VALUES ("global", "{\"prefix\": \"!\", \"url\": \"http://YOUR_IP\" ,\"owners\": [\"YOUR_ID\"]}", true, "YOUR_ID");

**Comment by msimon** [comment]
Thanks!
I was hoping to have it in the UI or from some config loaded from the env.

I'll add it manually, thank you for the example.
