### ISSUE TITLE
(root) Additional property name is not allowed

### ISSUE THREAD

**Issue by dingrins** [ZeppelinBot/Zeppelin#409]
I encountered an error stating "(root) Additional property name is not allowed" when executing the command "docker compose -f docker-compose.development.yml up".
Although I have filled in all the necessary attributes in the configuration file, it seems that there may be an issue.

Thanks.

**Comment by dingrins** [comment]
I believe I have resolved the issue by commenting out the "name" attribute in the compose files.

**Comment by rubyowo** [comment]
join the [Zeppelin Selfhosting server](discord.gg/uTcdUmF6Q7) to get proper support
